In [6]:
import torch
import numpy as np

In [3]:
torch.mps.is_available()

True

### 1.1 Создание тензоров

In [ ]:
# Создайте следующие тензоры:
# - Тензор размером 3x4, заполненный случайными числами от 0 до 1
# - Тензор размером 2x3x4, заполненный нулями
# - Тензор размером 5x5, заполненный единицами
# - Тензор размером 4x4 с числами от 0 до 15 (используйте reshape)

In [18]:
tensor_1 = torch.rand((3, 4))
tensor_2 = torch.zeros((2,3,4))
tensor_3 = torch.ones((5,5))
tensor_4 = torch.arange(16).reshape(4, 4)
print(tensor_1)
print(tensor_2)
print(tensor_3)
print(tensor_4)

tensor([[0.2430, 0.8861, 0.5832, 0.0907],
        [0.3712, 0.0036, 0.9773, 0.7168],
        [0.0282, 0.7931, 0.8265, 0.9595]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


### 1.2 Операции с тензорами 

In [ ]:
# Дано: тензор A размером 3x4 и тензор B размером 4x3
# Выполните:
# - Транспонирование тензора A
# - Матричное умножение A и B
# - Поэлементное умножение A и транспонированного B
# - Вычислите сумму всех элементов тензора A

In [ ]:
A = torch.rand((3,4))
B = torch.rand((4,3))
print(f'Тензор A {A}')
print(f'Тензор B {B}')
transpose_A = A.T
print(f'Транспонирование тензора A {A.T}')
print(f'Матричное умножение {A@B}')
print(f'Поэлементное умножение {A * B.T}')
print(f'Сумма всех элементов тензора A {A.sum()}')

Тензор A tensor([[0.6150, 0.6035, 0.7273, 0.7167],
        [0.8669, 0.1571, 0.9552, 0.8950],
        [0.2801, 0.4825, 0.8888, 0.8084]])
Тензор B tensor([[0.9226, 0.2244, 0.4845],
        [0.3047, 0.0194, 0.7771],
        [0.7281, 0.0448, 0.3868],
        [0.2572, 0.6401, 0.2455]])
Транспонирование тензора A tensor([[0.6150, 0.8669, 0.2801],
        [0.6035, 0.1571, 0.4825],
        [0.7273, 0.9552, 0.8888],
        [0.7167, 0.8950, 0.8084]])
Матричное умножение tensor([[1.4652, 0.6411, 1.2243],
        [1.7733, 0.8133, 1.1313],
        [1.2606, 0.6295, 1.0530]])
Поэлементное умножение tensor([[0.5674, 0.1839, 0.5295, 0.1844],
        [0.1946, 0.0031, 0.0428, 0.5729],
        [0.1357, 0.3750, 0.3438, 0.1985]])
Сумма всех элементов тензора A 7.9965291023254395


### 1.3 Индексация и срезы

In [ ]:
# Создайте тензор размером 5x5x5
# Извлеките:
# - Первую строку
# - Последний столбец
# - Подматрицу размером 2x2 из центра тензора
# - Все элементы с четными индексами

In [40]:
tensor = torch.rand((5,5,5))
print(tensor)
print(f'Первая строка {tensor[0,0,:]}')
print(f'Последний столбец {tensor[-1,:,-1]}')
print(f'Подматрицу размером 2x2 из центра тензора {tensor[2, 2:4, 2:4]}')
print(f'Все элементы с четными индексами {tensor[::2,::2,::2]}')

tensor([[[0.0294, 0.4979, 0.4228, 0.1569, 0.7464],
         [0.3173, 0.0812, 0.4979, 0.2503, 0.1472],
         [0.2081, 0.4922, 0.5050, 0.5195, 0.4762],
         [0.1632, 0.3287, 0.0403, 0.7593, 0.8516],
         [0.8829, 0.6664, 0.0374, 0.2552, 0.3323]],

        [[0.9377, 0.1492, 0.3386, 0.6423, 0.9237],
         [0.5548, 0.4626, 0.9081, 0.8596, 0.4379],
         [0.6247, 0.1456, 0.8481, 0.1476, 0.0369],
         [0.1112, 0.4059, 0.5818, 0.0812, 0.2243],
         [0.0620, 0.9926, 0.7441, 0.9787, 0.1074]],

        [[0.9173, 0.6481, 0.9337, 0.5209, 0.5910],
         [0.2003, 0.8129, 0.2740, 0.8387, 0.1861],
         [0.3620, 0.8144, 0.8772, 0.7058, 0.2404],
         [0.3808, 0.6714, 0.8524, 0.7642, 0.1690],
         [0.9203, 0.6630, 0.2361, 0.3544, 0.0545]],

        [[0.1023, 0.9091, 0.0835, 0.4214, 0.7572],
         [0.4007, 0.4880, 0.6041, 0.5025, 0.5058],
         [0.6929, 0.4103, 0.3995, 0.6174, 0.5394],
         [0.9944, 0.2813, 0.9813, 0.6177, 0.8199],
         [0.5029, 0.8649,

### 1.4 Работа с формами

In [ ]:
# Создайте тензор размером 24 элемента
# Преобразуйте его в формы:
# - 2x12
# - 3x8
# - 4x6
# - 2x3x4
# - 2x2x2x3

In [44]:
tensor_for_reshape = torch.arange(24)
print(tensor_for_reshape)
print(tensor_for_reshape.reshape((2,12)))
print(tensor_for_reshape.reshape((3,8)))
print(tensor_for_reshape.reshape((4,6)))
print(tensor_for_reshape.reshape((2,3,4)))
print(tensor_for_reshape.reshape((2,2,2,3)))

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23]])
tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[[ 0,  1,  2],
          [ 3,  4,  5]],

         [[ 6,  7,  8],
          [ 9, 10, 11]]],


        [[[12, 13, 14],
          [15, 16, 17]],

         [[18, 19, 20],
          [21, 22, 23]]]])
